### ISSUE TITLE
0.10 todo list

### ISSUE THREAD

**Issue by apsun** [apsun/NekoSMS#20]
To do:

- [ ] ~~Add filter list import feature~~
- [ ] ~~Add filter whitelist mode~~
- [x] Add wildcard pattern mode
- [x] Implement notification merging
- [x] Change activities to fragments, use nav drawer
- [x] Change filters to match both sender and body fields
- [x] Remove external storage permissions
- [x] Remove backup feature
- [x] Remove debug mode toggle
- [x] Fix Xposed SharedPreference access

Known bugs (to be fixed before release):

- [x] Displaying snackbar -> changing to filter list -> FAB not aligned, clicking snackbar action causes crash
- [x] Rotating screen with drawer open -> drawer stays open, icon changes to closed state
- [x] List dividers don't animate with cell contents

**Comment by apsun** [comment]
Reasons for dropped features:

**Filter lists**: Complicated to implement, almost zero expected users. Costs outweigh benefits.

**Whitelist mode**: With dual sender/body filters, this is no longer necessary. Just use a more complex regex if you need this. Adding support for whitelist filters would also require filter ordering, and significantly adds to UI complexity.

**Comment by apsun** [comment]
0.10.0 has been released!
